[package]
name = "rusty_dt"
version = "0.1.0"
authors = ["Sabree Blackmon <sabree@heavypackets.sh>"]
edition = "2018"

[dependencies]

[dev-dependencies]
uuid = { version = "0.6", features = ["v4"] }
